import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");

test("connection UI separates OpenCLI browser reads from QR and account authorization callbacks", () => {
  const actions = read("core/app/src/components/desktop-v627/connection-action-row.tsx");
  const domainAction = read("core/app/src/components/desktop-v627/domain-binding-action.tsx");
  const domainSop = read("core/app/src/components/desktop-v627/domain-binding-sop.tsx");
  const unbindDialog = read("core/app/src/components/desktop-v627/domain-unbind-dialog.tsx");
  const domainRuntime = read("core/agent/src/connections/domain-binding-verification.js");
  const sitePublication = read("core/agent/src/connections/verification-site-publication.js");
  const publicMailSender = read("core/agent/src/connections/mail/public-test-sender.js");
  const operationSop = read("core/app/src/components/desktop-v627/connection-operation-sop.tsx");
  const mailPage = read("core/app/src/components/desktop-v627/mail-page.tsx");
  const sync = read("core/app/src/components/desktop-v627/use-connection-status-sync.ts");
  const wechat = read("core/app/src/components/wechat-connect-panel.tsx");
  const wechatRuntime = read("core/agent/src/channels/wechat/connector.ts");
  const xiaohongshu = read("core/agent/src/channels/xiaohongshu/opencli-provider.js");
  const twitter = read("core/agent/src/channels/twitter/opencli-provider.js");
  const xiaohongshuRuntime = read("core/agent/src/channels/xiaohongshu/channel.js");
  const registry = JSON.parse(read("registry/connections.json"));
  const xiaohongshuConnection = registry.connections.find((connection) => connection.id === "xiaohongshu");
  const twitterConnection = registry.connections.find((connection) => connection.id === "twitter");
  assert.match(sync, /2 \* 60_000/);
  assert.match(actions, /重新连接/);
  assert.match(actions, /等待授权/);
  assert.match(domainAction, /移除域名绑定/);
  assert.match(domainAction, /platformDomainBound/);
  assert.match(domainAction, /BINDING_TIMEOUT_MS = 3 \* 60_000/);
  assert.match(domainAction, /\/api\/connections\/\$\{id\}\/status/);
  assert.match(domainAction, /domain-binding/);
  assert.doesNotMatch(domainAction, /window\.confirm/);
  assert.match(domainRuntime, /确认平台授权/);
  assert.match(domainRuntime, /查看验证发布/);
  assert.match(domainRuntime, /查看测试收到的邮件/);
  assert.match(domainRuntime, /createVerificationSitePublication/);
  assert.match(sitePublication, /page-thumbnail-desktop\.png/);
  assert.match(sitePublication, /page-thumbnail-mobile\.png/);
  assert.match(sitePublication, /Personal Agent Node · 公网入口已就绪/);
  assert.match(publicMailSender, /testemailsender\.com\/api\/tools\/test-email\/sends/);
  assert.doesNotMatch(publicMailSender, /cloud-resources|domain-verification\/mail/);
  assert.match(mailPage, /searchParams\.get\("message"\)/);
  assert.match(domainSop, /QRCode\.toDataURL/);
  assert.match(unbindDialog, /role="alertdialog"/);
  assert.match(unbindDialog, /本机数据不会删除/);
  assert.match(wechat, /重新生成二维码/);
  assert.match(wechat, /剩余/);
  assert.match(wechat, /ConnectionOperationSop/);
  assert.match(wechat, /生成登录二维码/);
  assert.match(wechat, /手机确认连接/);
  assert.match(actions, /OpenCliAction/);
  assert.match(actions, /ConnectionOperationSop/);
  assert.match(actions, /检测浏览器操作/);
  assert.match(actions, /校验平台只读能力/);
  assert.match(actions, /确认工作区授权/);
  assert.match(operationSop, /domain-sop-steps/);
  assert.match(actions, /\/api\/connections\/\$\{connection\.id\}\/open/);
  assert.match(actions, /修复浏览器连接/);
  assert.doesNotMatch(actions, /npm install|查看官方安装说明/);
  assert.doesNotMatch(actions, /XiaohongshuConnectPanel|xiaohongshu\/login/);
  assert.match(xiaohongshu, /loginStateInspected: false/);
  assert.match(twitter, /loginStateInspected: false/);
  assert.doesNotMatch(xiaohongshu, /authStatus|startLogin|pollLogin|qrImage/);
  assert.doesNotMatch(twitter, /authStatus|startLogin|pollLogin|qrImage/);
  assert.equal(xiaohongshuConnection.accessMode, "browser");
  assert.equal(twitterConnection.accessMode, "browser");
  assert.equal(xiaohongshuConnection.skillName, "social-browser-read");
  assert.equal(twitterConnection.skillName, "social-browser-read");
  assert.match(wechatRuntime, /LOGIN_SESSION_TIMEOUT_MS = 2 \* 60 \* 1000/);
  assert.match(wechatRuntime, /status === "scaned" \? "scanned"/);
  assert.match(xiaohongshuRuntime, /SESSION_TTL_MS = 2 \* 60 \* 1000/);
});

test("personal WeChat is independent from WeChat claw and configures a Qianxun-backed access policy", () => {
  const registry = JSON.parse(read("registry/connections.json"));
  const claw = registry.connections.find((connection) => connection.id === "wechat");
  const personal = registry.connections.find((connection) => connection.id === "wechat-personal");
  const action = read("core/app/src/components/desktop-v627/personal-wechat-action.tsx");
  const setupGuide = read("core/app/src/components/desktop-v627/personal-wechat-setup-guide.tsx");
  const connectivityTest = read("core/app/src/components/desktop-v627/personal-wechat-connectivity-test.tsx");
  const policy = read("core/app/src/components/desktop-v627/personal-wechat-policy.tsx");
  const desktopCss = read("core/app/src/app/desktop-v72.css");
  const historyPage = read("core/app/src/components/desktop-v627/personal-wechat-history-page.tsx");
  const historyHook = read("core/app/src/components/desktop-v627/use-personal-wechat-history.ts");
  const historyThread = read("core/app/src/components/desktop-v627/personal-wechat-history-thread.tsx");
  const server = read("core/agent/src/server/server.ts");
  assert.equal(claw.name, "微信 claw");
  assert.equal(claw.capabilities.some((capability) => capability.includes("千寻")), false);
  assert.equal(personal.name, "个人微信");
  assert.match(personal.description, /不下载、不启动也不分发千寻 Pro 二进制/);
  assert.match(action, /wechat-personal\/detect/);
  assert.match(action, /wechat-personal\/setup/);
  assert.match(action, /wechat-personal\/directory/);
  assert.match(action, /ConnectionOperationSop/);
  assert.match(action, /读取联系人与群/);
  assert.match(action, /href="\/app\/connections\/wechat-personal"/);
  assert.match(action, /最近 100 条记录/);
  assert.match(setupGuide, /daenmax\.github\.io\/qxpro-doc\/doc\/start/);
  assert.match(setupGuide, /千寻 Pro 官方文档/);
  assert.match(setupGuide, /配置消息回调/);
  assert.match(setupGuide, /复制个人微信消息回调地址/);
  assert.match(setupGuide, /target="_blank" rel="noreferrer"/);
  assert.match(setupGuide, /aria-label="千寻服务端口"/);
  assert.match(setupGuide, /inputMode="numeric"/);
  assert.match(action, /http:\/\/127\.0\.0\.1:\$\{port\}/);
  assert.match(action, /port >= 1 && port <= 65_535/);
  assert.match(action, /接收测试消息/);
  assert.match(action, /发送测试回复/);
  assert.match(connectivityTest, /文件传输助手/);
  assert.match(connectivityTest, /确认发送测试回复/);
  assert.match(connectivityTest, /1_500/);
  assert.match(server, /savedQianxunConfig\?\.baseUrl \|\| "http:\/\/127\.0\.0\.1:8055"/);
  assert.match(server, /wechat-personal\/connectivity-test\/start/);
  assert.match(server, /wechat-personal\/connectivity-test\/reply-plan/);
  assert.match(server, /wechat-personal\/connectivity-test\/reply/);
  assert.match(policy, /仅显示脱敏标识/);
  assert.match(policy, /选择这位联系人可以在哪些场景触发 Agent/);
  assert.match(policy, /选择群聊以及群里的触发方式/);
  assert.match(policy, /默认拒绝/);
  assert.match(policy, /直接选择下拉项即可授权/);
  assert.match(policy, /option value="none">不允许/);
  assert.doesNotMatch(policy, /type="checkbox"|disabled=\{!contact\.scope\}|disabled=\{!group\.trigger\}/);
  assert.match(desktopCss, /personal-wechat-policy-grid \{[^}]*max-height: min\(480px, 55vh\);[^}]*overflow-y: auto/);
  assert.match(desktopCss, /personal-wechat-policy legend \{[^}]*float: left;[^}]*background: #fff/);
  assert.match(server, /wechat-personal\/policy/);
  assert.match(server, /wechat-personal\/setup/);
  assert.match(server, /wechat-personal\/conversations/);
  assert.match(server, /wechat-personal\/history/);
  assert.match(server, /api\/internal\/channels\/wechat-personal\/callback/);
  assert.match(server, /127\.0\.0\.1:\$\{config\.port\}/);
  assert.match(server, /handleChannelMessage\("wechat-personal"/);
  assert.match(historyPage, /PersonalWechatHistoryConversations/);
  assert.match(historyPage, /PersonalWechatHistoryThread/);
  assert.match(historyPage, /还没有个人微信聊天记录/);
  assert.match(historyHook, /conversations\?limit=\$\{CONVERSATION_PAGE_SIZE\}/);
  assert.match(historyHook, /history\?conversation=/);
  assert.match(historyHook, /historyRequest/);
  assert.match(historyThread, /只读历史/);
  assert.match(historyThread, /当前无法接收新消息/);
});

test("Notion runtime uses the official headless login handoff and login poll", () => {
  const runtime = read("core/agent/src/connections/notion-cli.js");
  const skill = read("skills/personal-agent/references/connectors/notion.md");
  assert.match(runtime, /\["login", "--no-browser"\]/);
  assert.match(runtime, /\["login", "poll"\]/);
  assert.match(runtime, /openExternalUrl/);
  assert.match(skill, /ntn login --no-browser/);
  assert.match(skill, /ntn login poll/);
  assert.match(skill, /两分钟/);
});

test("domain connector skills describe completion callbacks for bind and remove", () => {
  for (const id of ["mail", "sites"]) {
    const skill = read(`skills/personal-agent/references/connectors/${id}.md`);
    assert.match(skill, /持续检查/);
    assert.match(skill, /状态回调/);
  }
});

test("connection directory separates all connections from connections with effective capabilities", () => {
  const page = read("core/app/src/components/desktop-v627/connections-page.tsx");
  const viewSwitch = read("core/app/src/components/desktop-v627/connection-view-switch.tsx");
  const css = read("core/app/src/app/desktop-v72.css");
  assert.match(page, /effectiveStates = new Set\(\["connected", "ready", "available", "healthy"\]\)/);
  assert.match(page, /view === "all" \|\| isEffectiveConnection\(connection\)/);
  assert.match(page, /matchesView && matchesCategory/);
  assert.match(page, /暂无已生效连接/);
  assert.match(page, /const initialLoading = loading && !value/);
  assert.match(page, /initialLoading \? <LoadingState label="正在加载连接"/);
  assert.match(page, /正在加载连接/);
  assert.match(page, /setSelectedId\(id\)/);
  assert.match(page, /router\.replace\(`\/app\/connections\?connection=\$\{encodeURIComponent\(id\)\}`/);
  assert.match(page, /\{ scroll: false \}/);
  assert.match(viewSwitch, /role="group" aria-label="连接视图"/);
  assert.match(viewSwitch, /aria-pressed=\{value === "all"\}/);
  assert.match(viewSwitch, /aria-pressed=\{value === "effective"\}/);
  assert.match(css, /\.kv-grid > \.kv:last-child:nth-child\(odd\) \{ grid-column: 1 \/ -1; \}/);
});
