"use client";

import { useState } from "react";
import type { AutomationData } from "./types";
import { Empty, Heading, relativeTime, statusLabel, useJson } from "./shared";

export function AutomationsPage() {
  const { value, loading } = useJson<AutomationData>("/api/node/v1/client/automations"); const [selectedId, setSelectedId] = useState(""); const selected = value?.rules.find((item) => item.id === selectedId) || value?.rules[0];
  return <main><Heading eyebrow="自动化" title="自动化" copy={selected ? `下一次运行由 PA 按触发条件决定 · ${selected.name}` : "查看由 PA 管理的触发规则和最近执行结果。"} action={<div className="automation-engine-state"><span>引擎</span><strong>{loading ? "读取中" : "正常"}</strong><span>自动化</span><strong>{value?.counts.total || 0}</strong><span>最近运行</span><strong>{value?.counts.recentRuns || 0}</strong></div>} /><div className="automation-layout"><aside className="automation-list"><header><strong>自动化</strong><span>PA 管理</span></header>{value?.rules.map((item) => <button className={`automation-item${selected?.id === item.id ? " selected" : ""}`} onClick={() => setSelectedId(item.id)} key={item.id}><span className="automation-symbol">{item.name.slice(0, 1)}</span><span><strong>{item.name}</strong><small>{item.eventType}</small></span><i className={item.enabled ? "" : "paused"}>{item.enabled ? "启用" : "暂停"}</i></button>)}</aside><article className="automation-detail">{selected ? <><header><div><span className="pa-eyebrow">只读自动化</span><h2>{selected.name}</h2><p>{selected.description}</p></div><span className="pa-status">{selected.enabled ? "启用" : "暂停"}</span></header><section className="automation-definition"><div><span>触发方式</span><strong>{selected.eventType}</strong><small>由 PA 管理</small></div><div><span>规则版本</span><strong>v{selected.version}</strong><small>{relativeTime(selected.updatedAt)}更新</small></div></section><section className="automation-runs"><header><strong>最近运行</strong><span>只读记录</span></header>{selected.recentRuns.map((run) => <div className="automation-run" key={run.id}><time>{relativeTime(run.createdAt)}</time><span>{run.reason || statusLabel(run.status)}</span><b>{run.matched ? "已匹配" : "未触发"}</b></div>)}</section></> : <Empty text="还没有自动化规则" />}</article></div></main>;
}
