import { ArrowDownAZ, ArrowUpAZ, X } from "lucide-react";
import { Button } from "../desktop-v72/primitives";
import { useEffect, useState } from "react";

export function DataColumnPanel({ column, columns, label, filter, sort, onApply, onClear, onClose, onColumnChange }: { column: string; columns: string[]; label: string; filter: string; sort?: { column: string; direction: "asc" | "desc" }; onApply: (column: string, filter: string, direction?: "asc" | "desc") => void; onClear: (column: string) => void; onClose: () => void; onColumnChange: (column: string) => void }) {
  const [query, setQuery] = useState(filter);
  const [direction, setDirection] = useState<"asc" | "desc">();
  useEffect(() => { setQuery(filter); setDirection(sort?.column === column ? sort.direction : undefined); }, [column, filter, sort]);
  return <section className="data-control-panel" aria-label={`${label}筛选与排序`}><header><div><span>列操作</span><strong>{label}</strong></div><button className="icon-button" type="button" onClick={onClose} aria-label="关闭列操作"><X /></button></header><label className="data-field"><span>操作列</span><select value={column} onChange={(event) => onColumnChange(event.target.value)}>{columns.map((item) => <option value={item} key={item}>{item}</option>)}</select></label><div className="data-control-group"><span>排序</span><div className="data-sort-actions"><button className={direction === "asc" ? "active" : ""} type="button" onClick={() => setDirection(direction === "asc" ? undefined : "asc")}><ArrowDownAZ />升序</button><button className={direction === "desc" ? "active" : ""} type="button" onClick={() => setDirection(direction === "desc" ? undefined : "desc")}><ArrowUpAZ />降序</button></div></div><div className="data-control-group"><span>筛选内容</span><label className="data-field value-filter"><span>包含值</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`输入${label}中的值`} /></label><small className="data-hint">输入值后由本机数据服务参数化筛选。</small></div><footer><Button onClick={() => onClear(column)}>清除</Button><Button variant="primary" onClick={() => onApply(column, query.trim(), direction)}>应用</Button></footer></section>;
}

export function DataVisibilityPanel({ columns, visible, display, onChange, onClose }: { columns: string[]; visible: string[]; display: (column: string) => string; onChange: (columns: string[]) => void; onClose: () => void }) {
  const toggle = (column: string) => { if (visible.includes(column) && visible.length === 1) return; onChange(visible.includes(column) ? visible.filter((item) => item !== column) : columns.filter((item) => visible.includes(item) || item === column)); };
  return <section className="data-control-panel column-visibility" aria-label="选择显示列"><header><div><span>当前工作表</span><strong>显示列</strong></div><button className="icon-button" type="button" onClick={onClose} aria-label="关闭列选择"><X /></button></header><div className="data-choice-list">{columns.map((column) => <label key={column}><input type="checkbox" checked={visible.includes(column)} onChange={() => toggle(column)} /><span>{display(column)}</span></label>)}</div><p className="data-hint">至少保留一列；显示设置不会改变数据表结构。</p><footer><Button variant="primary" onClick={onClose}>完成</Button></footer></section>;
}
