"use client";

import { useState, type FormEvent } from "react";
import { validateLocalPasswordInput } from "@/lib/setup-tasks";
import type { RuntimeData } from "./types";
import { Heading, errorMessage, useJson } from "./shared";

export function SettingsPage() {
  const runtime = useJson<RuntimeData>("/api/node/v1/client/runtime"); const [password, setPassword] = useState(""); const [confirmation, setConfirmation] = useState(""); const [show, setShow] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("填写并确认新密码"); const issue = validateLocalPasswordInput(password, confirmation);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (issue) { setMessage(issue.replace("本机登录密码", "访问密码")); return; } setSaving(true); try { const post = async (phase: string, body: object) => { const response = await fetch(`/api/system/setup/actions/installation.local-auth/${phase}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json(); if (!response.ok || !payload.operation) throw new Error(payload.error?.message || "更新失败"); return payload.operation; }; const plan = await post("plan", {}); await post("approve", { operationId: plan.id, digest: plan.digest, approved: true }); await post("execute", { operationId: plan.id, digest: plan.digest, input: { password, confirmation } }); setPassword(""); setConfirmation(""); setMessage("访问密码已更新，其他设备需要重新登录"); } catch (cause) { setMessage(errorMessage(cause)); } finally { setSaving(false); } };
  return <main><Heading eyebrow="本机设置" title="系统设置" copy="管理这台电脑与其他设备访问 PA 的方式。" action={<span className="pa-status local-access-status">本机直接访问</span>} /><div className="system-settings-layout"><section className="system-settings-main"><article className="access-boundary-card"><div><span className="pa-eyebrow">访问方式</span><h2>这台电脑无需登录</h2><p>桌面客户端只在本机打开，始终直接进入。访问密码仅用于手机或通过私有域名访问 PA。</p></div><dl><div><dt>当前桌面客户端</dt><dd><i className="access-state-dot direct" />直接访问</dd></div><div><dt>手机与私有域名</dt><dd><i className="access-state-dot protected" />密码保护</dd></div></dl></article><form className="password-settings-card" onSubmit={submit} noValidate><header><span className="pa-eyebrow">访问安全</span><h2>修改访问密码</h2><p>忘记密码时可以直接在这台电脑上重新设置，无需输入旧密码。</p></header><div className="password-fields"><label><span>新访问密码</span><span className="password-input-wrap"><input type={show ? "text" : "password"} autoComplete="new-password" minLength={12} maxLength={256} placeholder="至少 12 个字符" value={password} onChange={(event) => setPassword(event.target.value)} /><button type="button" className="password-reveal" onClick={() => setShow((value) => !value)}>{show ? "隐藏" : "显示"}</button></span></label><label><span>确认新密码</span><span className="password-input-wrap"><input type={show ? "text" : "password"} autoComplete="new-password" minLength={12} maxLength={256} placeholder="再次输入新密码" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} /></span></label></div><p className="password-requirement">至少 12 个字符。密码只在本机保存为不可逆校验信息。</p><div className="password-action-row"><button className="pa-button primary" type="submit" disabled={saving || Boolean(issue)}>{saving ? "正在更新…" : "更新访问密码"}</button><span role="status">{message}</span></div><aside className="session-warning"><strong>更新后会发生什么</strong><p>手机和其他设备上的现有登录会失效，需要使用新密码重新进入。当前桌面客户端不受影响。</p></aside></form></section><aside className="system-settings-aside"><article><span className="pa-eyebrow">客户端</span><h2>Personal Agent</h2><dl><div><dt>版本</dt><dd>{runtime.value?.version || "读取中"}</dd></div><div><dt>工作区</dt><dd>本机可用</dd></div><div><dt>更新</dt><dd>由安装包管理</dd></div></dl></article><article className="trusted-device-note"><span>⌂</span><div><strong>本机可信入口</strong><p>只有安装在这台电脑上的桌面客户端可以免登录修改访问密码。</p></div></article></aside></div></main>;
}
