"use client";

import { useState } from "react";
import type { Skill, SkillCategory } from "./types";
import { Heading, useJson } from "./shared";

export function SkillsPage() {
  const { value, loading } = useJson<{ categories: SkillCategory[]; skills: Skill[] }>("/api/skills"); const [category, setCategory] = useState("all"); const [query, setQuery] = useState(""); const categories = value?.categories || []; const skills = value?.skills || []; const visible = skills.filter((item) => (category === "all" || item.category === category) && (!query || `${item.name} ${item.description}`.toLowerCase().includes(query.toLowerCase())));
  return <main><Heading eyebrow="技能" title="PA 可使用的能力" copy="按要完成的事情查找技能。涉及联网、内容生成或受控操作时，会在执行前说明。" action={<div className="skill-summary"><strong>{categories.length}</strong><span>类</span><strong>{skills.length}</strong><span>项技能</span></div>} /><div className="skill-toolbar"><div className="skill-category-filters" role="group" aria-label="按技能类别筛选"><button className={category === "all" ? "active" : ""} onClick={() => setCategory("all")}>全部 <span>{skills.length}</span></button>{categories.map((item) => <button className={category === item.id ? "active" : ""} onClick={() => setCategory(item.id)} key={item.id}>{item.label}<span>{skills.filter((skill) => skill.category === item.id).length}</span></button>)}</div><label className="skill-search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索技能或用途" /></label></div><div className="skill-catalog">{categories.filter((item) => category === "all" || item.id === category).map((item) => { const items = visible.filter((skill) => skill.category === item.id); return items.length ? <section className="skill-category-section" key={item.id}><header><div><span>{item.label}</span><p>{item.description}</p></div><b>{items.length}</b></header><div className="skill-cards">{items.map((skill) => <article className="skill-card" key={skill.name}><span className="skill-card-icon">{skill.name.slice(0, 2)}</span><div className="skill-card-copy"><h2>{skill.name}</h2><p>{skill.description}</p><div className="skill-meta"><span>本机技能</span>{skill.risks?.length ? <span>操作前确认</span> : null}</div></div></article>)}</div></section> : null; })}</div>{!loading && !visible.length ? <div className="skill-empty"><strong>没有找到相关技能</strong><p>换一个关键词或分类再试。</p><button onClick={() => { setQuery(""); setCategory("all"); }}>清除筛选</button></div> : null}</main>;
}
