/var/log/private-site-edge/traffic-*.log {
    daily
    rotate 7
    missingok
    notifempty
    compress
    delaycompress
    su root @NGINX_GROUP@
    create 0640 root @NGINX_GROUP@
    sharedscripts
    postrotate
        /bin/systemctl kill -s USR1 nginx.service >/dev/null 2>&1 || true
    endscript
}
