#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";

const args = parseArgs(process.argv.slice(2));
const inputPath = path.resolve(args.input || "");
const outputPath = path.resolve(args.out || "");
if (!args.input || !args.out) fail("usage: render-report --input <report.json> --out <report.html> [--force]");
if (!fs.existsSync(inputPath)) fail(`input file not found: ${inputPath}`);
if (fs.existsSync(outputPath) && !args.force) fail(`output already exists: ${outputPath}; pass --force to replace it`);

const report = normalizeReport(JSON.parse(fs.readFileSync(inputPath, "utf8")));
const html = renderReport(report);
fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, html, "utf8");
process.stdout.write(`${JSON.stringify({ ok: true, output: outputPath, charts: report.charts.length, bytes: Buffer.byteLength(html) })}\n`);

function normalizeReport(input) {
  if (!input || typeof input !== "object" || Array.isArray(input)) fail("report input must be a JSON object");
  const title = text(input.title, 160);
  if (!title) fail("report title is required");
  const charts = array(input.charts).map((chart, index) => normalizeChart(chart, index));
  if (!charts.length) fail("at least one chart is required");
  return {
    title,
    subtitle: text(input.subtitle, 300),
    period: text(input.period, 100),
    generatedAt: validDate(input.generatedAt) || new Date().toISOString(),
    summary: text(input.summary, 1_500),
    currency: text(input.currency, 12) || "CNY",
    metrics: array(input.metrics).slice(0, 8).map((metric) => ({
      label: text(metric?.label, 80) || "指标",
      value: scalar(metric?.value),
      delta: text(metric?.delta, 80),
      note: text(metric?.note, 160),
    })),
    charts,
    notes: array(input.notes).slice(0, 20).map((note) => text(note, 500)).filter(Boolean),
    source: text(input.source, 300),
  };
}

function normalizeChart(input, index) {
  if (!input || typeof input !== "object" || Array.isArray(input)) fail(`chart ${index + 1} must be an object`);
  const type = input.type === "bar" ? "bar" : input.type === "line" ? "line" : "";
  if (!type) fail(`chart ${index + 1} type must be line or bar`);
  const labels = array(input.labels).map((label) => text(label, 80));
  if (labels.length < 2 || labels.length > 60) fail(`chart ${index + 1} requires 2 to 60 labels`);
  const series = array(input.series).slice(0, 5).map((item, seriesIndex) => {
    const values = array(item?.values).map(Number);
    if (values.length !== labels.length || values.some((value) => !Number.isFinite(value))) fail(`chart ${index + 1} series ${seriesIndex + 1} must contain one finite number per label`);
    return { name: text(item?.name, 80) || `系列 ${seriesIndex + 1}`, values };
  });
  if (!series.length) fail(`chart ${index + 1} requires at least one series`);
  return {
    type,
    title: text(input.title, 160) || `图表 ${index + 1}`,
    description: text(input.description, 500),
    unit: text(input.unit, 24),
    labels,
    series,
  };
}

function renderReport(report) {
  return `<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
  <meta name="color-scheme" content="light">
  <meta name="robots" content="noindex,nofollow">
  <title>${escapeHtml(report.title)}</title>
  <style>${reportStyles()}</style>
</head>
<body>
  <main class="report-shell">
    <header class="report-header">
      <a class="report-home" href="/app" aria-label="返回 Personal Agent"><span aria-hidden="true">PA</span><strong>返回 Personal Agent</strong></a>
      <p class="report-kicker">ONLINE PAGES REPORT</p>
      <h1>${escapeHtml(report.title)}</h1>
      ${report.subtitle ? `<p class="report-subtitle">${escapeHtml(report.subtitle)}</p>` : ""}
      <div class="report-meta"><span>${escapeHtml(report.period || "分析报告")}</span><time datetime="${escapeHtml(report.generatedAt)}">${escapeHtml(formatDate(report.generatedAt))}</time></div>
    </header>
    ${report.summary ? `<section class="report-summary"><strong>摘要</strong><p>${escapeHtml(report.summary)}</p></section>` : ""}
    ${report.metrics.length ? `<section class="metric-grid" aria-label="关键指标">${report.metrics.map(renderMetric).join("")}</section>` : ""}
    <section class="chart-list">${report.charts.map((chart, index) => renderChart(chart, index, report.currency)).join("")}</section>
    ${report.notes.length ? `<section class="report-notes"><h2>说明</h2><ol>${report.notes.map((note) => `<li>${escapeHtml(note)}</li>`).join("")}</ol></section>` : ""}
    <footer class="report-footer"><span>${report.source ? `数据来源：${escapeHtml(report.source)}` : "结构化数据报告"}</span><span>Generated by Personal Agent</span></footer>
  </main>
  <script>${reportScript()}</script>
</body>
</html>`;
}

function renderMetric(metric) {
  const deltaClass = /^-/.test(metric.delta) ? "negative" : metric.delta ? "positive" : "";
  return `<article class="metric"><span>${escapeHtml(metric.label)}</span><strong>${escapeHtml(String(metric.value))}</strong>${metric.delta ? `<small class="${deltaClass}">${escapeHtml(metric.delta)}</small>` : ""}${metric.note ? `<p>${escapeHtml(metric.note)}</p>` : ""}</article>`;
}

function renderChart(chart, index, currency) {
  const id = `chart-${index + 1}`;
  return `<article class="chart-card" id="${id}">
    <header><div><span>${chart.type === "line" ? "趋势" : "比较"}</span><h2>${escapeHtml(chart.title)}</h2></div><div class="chart-legend">${chart.series.map((series, seriesIndex) => `<span><i style="--series:${palette(seriesIndex)}"></i>${escapeHtml(series.name)}</span>`).join("")}</div></header>
    ${chart.description ? `<p class="chart-description">${escapeHtml(chart.description)}</p>` : ""}
    <div class="chart-scroll"><div class="chart-stage">${chart.type === "line" ? renderLineChart(chart) : renderBarChart(chart)}<output class="chart-tooltip" aria-live="polite">点击或聚焦数据点查看数值</output></div></div>
    ${renderDataTable(chart, currency)}
  </article>`;
}

function renderLineChart(chart) {
  const frame = chartFrame(chart);
  const paths = chart.series.map((series, seriesIndex) => {
    const points = series.values.map((value, valueIndex) => [frame.x(valueIndex), frame.y(value)]);
    const pathData = points.map(([x, y], pointIndex) => `${pointIndex ? "L" : "M"}${round(x)} ${round(y)}`).join(" ");
    const color = palette(seriesIndex);
    return `<path class="series-line" d="${pathData}" stroke="${color}"></path>${points.map(([x, y], valueIndex) => `<g class="chart-point" tabindex="0" role="img" aria-label="${escapeHtml(`${chart.labels[valueIndex]}，${series.name}，${series.values[valueIndex]}${chart.unit}`)}" data-label="${escapeHtml(`${chart.labels[valueIndex]} · ${series.name}`)}" data-value="${escapeHtml(`${formatNumber(series.values[valueIndex])}${chart.unit}`)}"><circle cx="${round(x)}" cy="${round(y)}" r="5" fill="${color}"></circle></g>`).join("")}`;
  }).join("");
  return `<svg class="report-chart" viewBox="0 0 720 320" role="img" aria-labelledby="${frame.id}-title ${frame.id}-desc"><title id="${frame.id}-title">${escapeHtml(chart.title)}</title><desc id="${frame.id}-desc">${escapeHtml(chart.description || "时间序列折线图")}</desc>${frame.grid}${paths}${frame.labels}</svg>`;
}

function renderBarChart(chart) {
  const frame = chartFrame(chart);
  const groupWidth = frame.plotWidth / chart.labels.length;
  const barGap = 4;
  const barWidth = Math.max(5, Math.min(34, (groupWidth - 12 - barGap * (chart.series.length - 1)) / chart.series.length));
  const bars = chart.labels.map((label, labelIndex) => chart.series.map((series, seriesIndex) => {
    const x = frame.left + labelIndex * groupWidth + (groupWidth - (barWidth * chart.series.length + barGap * (chart.series.length - 1))) / 2 + seriesIndex * (barWidth + barGap);
    const y = frame.y(series.values[labelIndex]);
    const height = Math.max(frame.bottom - y, 1);
    return `<g class="chart-point" tabindex="0" role="img" aria-label="${escapeHtml(`${label}，${series.name}，${series.values[labelIndex]}${chart.unit}`)}" data-label="${escapeHtml(`${label} · ${series.name}`)}" data-value="${escapeHtml(`${formatNumber(series.values[labelIndex])}${chart.unit}`)}"><rect x="${round(x)}" y="${round(y)}" width="${round(barWidth)}" height="${round(height)}" rx="2" fill="${palette(seriesIndex)}"></rect></g>`;
  }).join("")).join("");
  return `<svg class="report-chart" viewBox="0 0 720 320" role="img" aria-labelledby="${frame.id}-title ${frame.id}-desc"><title id="${frame.id}-title">${escapeHtml(chart.title)}</title><desc id="${frame.id}-desc">${escapeHtml(chart.description || "分组柱状图")}</desc>${frame.grid}${bars}${frame.labels}</svg>`;
}

function chartFrame(chart) {
  const width = 720;
  const height = 320;
  const left = 58;
  const right = 18;
  const top = 18;
  const bottom = 270;
  const values = chart.series.flatMap((series) => series.values);
  const rawMin = Math.min(...values, 0);
  const rawMax = Math.max(...values, 0);
  const spread = rawMax - rawMin || Math.max(Math.abs(rawMax), 1);
  const min = rawMin < 0 ? rawMin - spread * 0.08 : 0;
  const max = rawMax + spread * 0.1;
  const plotWidth = width - left - right;
  const plotHeight = bottom - top;
  const y = (value) => top + ((max - value) / (max - min || 1)) * plotHeight;
  const x = (index) => left + (chart.labels.length === 1 ? plotWidth / 2 : index * plotWidth / (chart.labels.length - 1));
  const ticks = Array.from({ length: 5 }, (_, index) => min + (max - min) * index / 4);
  const grid = ticks.map((tick) => `<line x1="${left}" y1="${round(y(tick))}" x2="${width - right}" y2="${round(y(tick))}" class="grid-line"></line><text x="${left - 9}" y="${round(y(tick) + 4)}" text-anchor="end" class="axis-label">${escapeHtml(shortNumber(tick))}</text>`).join("");
  const step = Math.max(1, Math.ceil(chart.labels.length / 8));
  const labels = chart.labels.map((label, index) => index % step === 0 || index === chart.labels.length - 1 ? `<text x="${round(chart.type === "bar" ? left + (index + .5) * plotWidth / chart.labels.length : x(index))}" y="298" text-anchor="middle" class="axis-label">${escapeHtml(shortLabel(label))}</text>` : "").join("");
  return { id: `svg-${hash(chart.title)}`, left, right, top, bottom, plotWidth, y, x, grid, labels };
}

function renderDataTable(chart, currency) {
  return `<details class="chart-data"><summary>查看图表数据</summary><div><table><thead><tr><th>项目</th>${chart.series.map((series) => `<th>${escapeHtml(series.name)}</th>`).join("")}</tr></thead><tbody>${chart.labels.map((label, index) => `<tr><th>${escapeHtml(label)}</th>${chart.series.map((series) => `<td>${escapeHtml(formatValue(series.values[index], chart.unit, currency))}</td>`).join("")}</tr>`).join("")}</tbody></table></div></details>`;
}

function reportStyles() {
  return `:root{color-scheme:light;--paper:#f3f4f1;--surface:#fff;--ink:#171b19;--muted:#68706b;--line:#d9ded9;--green:#156f67;--blue:#3465a4;--amber:#b7791f;--red:#b5473c;font-family:"Aptos","Segoe UI","PingFang SC","Microsoft YaHei",sans-serif;letter-spacing:0}*{box-sizing:border-box}html{background:var(--paper);scroll-behavior:smooth}body{margin:0;color:var(--ink);background:var(--paper)}a{color:inherit}.report-shell{width:min(100%,72rem);margin:0 auto;padding:clamp(1rem,4vw,3.5rem)}.report-header{border-top:5px solid var(--ink);border-bottom:1px solid var(--ink);padding:1rem 0 1.5rem}.report-home{width:max-content;display:inline-flex;align-items:center;gap:.55rem;text-decoration:none;color:var(--green);font-size:.75rem}.report-home span{width:1.8rem;height:1.8rem;display:grid;place-items:center;border:1px solid var(--green);font-weight:800}.report-kicker{margin:2rem 0 .5rem;color:var(--green);font-size:.68rem;font-weight:800}.report-header h1{max-width:18ch;margin:0;font-family:Georgia,"Songti SC",serif;font-size:clamp(2rem,6vw,4.4rem);font-weight:500;line-height:1.04}.report-subtitle{max-width:48rem;margin:1rem 0 0;color:var(--muted);font-size:clamp(.9rem,2vw,1.1rem);line-height:1.7}.report-meta{display:flex;justify-content:space-between;gap:1rem;margin-top:1.4rem;color:var(--muted);font-size:.72rem}.report-summary{display:grid;grid-template-columns:8rem minmax(0,1fr);gap:1rem;border-bottom:1px solid var(--line);padding:1.5rem 0}.report-summary strong{font-size:.75rem}.report-summary p{margin:0;color:#343a36;line-height:1.75}.metric-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:.65rem;padding:1.5rem 0}.metric{min-width:0;border:1px solid var(--line);border-top:3px solid var(--green);border-radius:6px;background:var(--surface);display:grid;align-content:start;gap:.3rem;padding:.85rem}.metric>span,.metric>small{color:var(--muted);font-size:.68rem}.metric>strong{overflow:hidden;text-overflow:ellipsis;font-size:1.35rem;font-variant-numeric:tabular-nums}.metric small.positive{color:var(--green)}.metric small.negative{color:var(--red)}.metric p{margin:.2rem 0 0;color:var(--muted);font-size:.7rem;line-height:1.5}.chart-list{display:grid;gap:1rem}.chart-card{min-width:0;overflow:hidden;border:1px solid var(--line);border-radius:6px;background:var(--surface)}.chart-card>header{display:flex;align-items:flex-end;justify-content:space-between;gap:1rem;border-bottom:1px solid var(--line);padding:1rem}.chart-card>header>div:first-child span{color:var(--green);font-size:.65rem;font-weight:800}.chart-card h2{margin:.15rem 0 0;font-size:1rem}.chart-legend{display:flex;align-items:center;justify-content:flex-end;gap:.75rem;flex-wrap:wrap;color:var(--muted);font-size:.65rem}.chart-legend span{display:inline-flex;align-items:center;gap:.3rem}.chart-legend i{width:.7rem;height:.18rem;background:var(--series)}.chart-description{margin:0;padding:.8rem 1rem 0;color:var(--muted);font-size:.75rem;line-height:1.65}.chart-scroll{max-width:100%;overflow-x:auto;overscroll-behavior-inline:contain;padding:.45rem 1rem .75rem}.chart-stage{width:100%;min-width:34rem}.report-chart{display:block;width:100%;height:auto;overflow:visible}.grid-line{stroke:#e3e7e3;stroke-width:1}.axis-label{fill:#778079;font:10px "Aptos","Segoe UI",sans-serif}.series-line{fill:none;stroke-width:2.5;stroke-linecap:round;stroke-linejoin:round}.chart-point{outline:none;cursor:pointer}.chart-point circle,.chart-point rect{transition:opacity .15s,stroke-width .15s}.chart-point:hover circle,.chart-point:focus circle,.chart-point:hover rect,.chart-point:focus rect{stroke:#171b19;stroke-width:2;opacity:.88}.chart-tooltip{display:block;min-height:1.7rem;border-top:1px solid var(--line);margin-top:.2rem;padding:.5rem .2rem 0;color:var(--muted);font-size:.7rem}.chart-tooltip strong{color:var(--ink)}.chart-data{border-top:1px solid var(--line);padding:.75rem 1rem}.chart-data summary{width:max-content;color:var(--green);cursor:pointer;font-size:.7rem;font-weight:700}.chart-data>div{max-width:100%;overflow-x:auto;overscroll-behavior-inline:contain;margin-top:.65rem}.chart-data table{width:100%;min-width:30rem;border-collapse:collapse;font-size:.7rem}.chart-data th,.chart-data td{border-bottom:1px solid var(--line);padding:.45rem;text-align:right;white-space:nowrap}.chart-data th:first-child{text-align:left}.report-notes{border-top:1px solid var(--ink);margin-top:1.5rem;padding-top:1rem}.report-notes h2{margin:0;font-size:.8rem}.report-notes ol{margin:.7rem 0 0;padding-left:1.25rem;color:var(--muted);font-size:.75rem;line-height:1.65}.report-footer{display:flex;justify-content:space-between;gap:1rem;border-top:1px solid var(--line);margin-top:2rem;padding-top:.8rem;color:var(--muted);font-size:.65rem}@media(max-width:720px){.report-shell{padding:1rem}.report-header h1{font-size:2.35rem}.report-summary{grid-template-columns:1fr;gap:.45rem}.metric-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.chart-card>header{align-items:flex-start;flex-direction:column}.chart-legend{justify-content:flex-start}.report-footer{align-items:flex-start;flex-direction:column}.chart-scroll{padding-inline:.75rem}}@media(max-width:380px){.metric-grid{grid-template-columns:1fr}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition:none!important}}`;
}

function reportScript() {
  return `for(const card of document.querySelectorAll('.chart-card')){const output=card.querySelector('.chart-tooltip');for(const point of card.querySelectorAll('.chart-point')){const show=()=>{output.innerHTML='<strong>'+escapeChart(point.dataset.label)+'</strong> · '+escapeChart(point.dataset.value)};point.addEventListener('pointerdown',show);point.addEventListener('focus',show)}}function escapeChart(value){return String(value||'').replace(/[&<>"']/g,(character)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]))}`;
}

function palette(index) { return ["#156f67", "#3465a4", "#b7791f", "#b5473c", "#6c5b8f"][index % 5]; }
function shortLabel(value) { const text = String(value); return text.length > 9 ? `${text.slice(0, 8)}...` : text; }
function shortNumber(value) { return Math.abs(value) >= 1_000_000 ? `${round(value / 1_000_000)}M` : Math.abs(value) >= 1_000 ? `${round(value / 1_000)}K` : String(round(value)); }
function formatNumber(value) { return new Intl.NumberFormat("zh-CN", { maximumFractionDigits: 2 }).format(value); }
function formatValue(value, unit, currency) { return unit ? `${formatNumber(value)}${unit}` : currency === "CNY" ? `¥${formatNumber(value)}` : formatNumber(value); }
function formatDate(value) { return new Intl.DateTimeFormat("zh-CN", { dateStyle: "long", timeStyle: "short", timeZone: "Asia/Shanghai" }).format(new Date(value)); }
function round(value) { return Math.round(value * 100) / 100; }
function hash(value) { let result = 0; for (const character of String(value)) result = (result * 31 + character.charCodeAt(0)) >>> 0; return result.toString(36); }
function scalar(value) { return typeof value === "number" && Number.isFinite(value) ? formatNumber(value) : text(value, 80); }
function validDate(value) { const date = new Date(value || ""); return Number.isNaN(date.getTime()) ? "" : date.toISOString(); }
function array(value) { return Array.isArray(value) ? value : []; }
function text(value, limit) { return String(value ?? "").trim().slice(0, limit); }
function escapeHtml(value) { return String(value ?? "").replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]); }
function parseArgs(values) { const result = {}; for (let index = 0; index < values.length; index += 1) { const item = values[index]; if (!item.startsWith("--")) continue; const key = item.slice(2); if (key === "force") result.force = true; else result[key] = values[index + 1], index += 1; } return result; }
function fail(message) { process.stderr.write(`${message}\n`); process.exit(1); }
